const cities = [
  "Auckland",
  "Christchurch",
  "Manukau City",
  "Wellington",
  "Northcote",
  "Hamilton",
  "Tauranga",
  "Lower Hutt",
  "Dunedin",
  "Palmerston North",
  "Napier",
  "New Plymouth",
  "Porirua",
  "Rotorua",
  "Whangarei",
  "Invercargill",
  "Nelson",
  "Upper Hutt",
  "Gisborne",
  "Paraparaumu",
  "Timaru",
  "Blenheim",
  "Taupo",
  "Cambridge",
  "Feilding",
  "Levin",
  "Rolleston",
  "Whakatane",
  "Richmond",
  "Havelock North",
  "Tokoroa",
  "Mosgiel",
  "Te Awamutu",
  "Waikanae",
  "Hawera",
  "Waiuku",
  "Paraparaumu Beach",
  "Wanaka",
  "Te Puke",
  "Greymouth",
  "Matamata",
  "Thames",
  "Kawerau",
  "Kerikeri",
  "Waitara",
  "Ngaruawahia",
  "Mount Maunganui",
  "Lincoln",
  "Kaitaia",
  "Stratford",
  "Alexandra",
  "Cromwell",
  "Warkworth",
  "Waihi",
  "Raumati Beach",
  "Marton",
  "Whitianga",
  "Tuakau",
  "Dargaville",
  "Katikati",
  "Westport",
  "Tauwhare",
  "Te Aroha",
  "Kaikohe",
  "Prebbleton",
  "Paeroa",
  "Whangamata",
  "Balclutha",
  "Snells Beach",
  "Turangi",
  "Raglan",
  "Foxton",
  "Darfield",
  "Ashhurst",
  "Hokitika",
  "Helensville",
  "Woodend",
  "Kihikihi",
  "Pahiatua",
  "Wakefield",
  "Ruakaka",
  "Winton",
  "Maraetai",
  "Te Anau",
  "Clive",
  "Oxford",
  "Pokeno",
  "Milton",
  "Waihi Beach",
  "Brightwater",
  "Leeston",
  "West Melton",
  "Waitangi",
];

export default cities;
